# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        heart rate variability: 5
        stress: 5
        mental health: 5
        sleep: 4
        psychology: 2
        psychiatry: 2

# 通知の閾値
score_threshold: 0
